export {
  CLIENT_ASSERTION_TYPE,
  JWT_BEARER_GRANT,
  JWT_BEARER_GRANT_COMPAT,
  RFC6749_AUTH_ERROR_URI,
  RFC6749_TOKEN_ERROR_URI,
  RFC7636_ERROR_URI,
  TOKEN_EXCHANGE_GRANT
} from "./domain/value-objects/oauth-protocol";

export const ACCESS_TOKEN_TTL_SECONDS = Number(process.env.ACCESS_TOKEN_TTL_SECONDS ?? 300);
export const AUTH_CODE_TTL_SECONDS = Number(process.env.AUTH_CODE_TTL_SECONDS ?? 60);
export const REQUEST_URI_TTL_SECONDS = Number(process.env.REQUEST_URI_TTL_SECONDS ?? 60);
export const REFRESH_TOKEN_TTL_SECONDS = Number(
  process.env.REFRESH_TOKEN_TTL_SECONDS ?? 3600
);
export const SIGNING_KEY_ROTATION_DAYS = Number(process.env.SIGNING_KEY_ROTATION_DAYS ?? 30);
export const SIGNING_KEY_RETENTION_DAYS = Number(process.env.SIGNING_KEY_RETENTION_DAYS ?? 45);
export const SIGNING_KEY_CACHE_SECONDS = Number(process.env.SIGNING_KEY_CACHE_SECONDS ?? 60);

export const AUTH_PROVIDER_JWT_MAX_TTL_SECONDS = Number(
  process.env.AUTH_PROVIDER_JWT_MAX_TTL_SECONDS ?? 300
);
export const PASSWORD_GRANT_ENABLED = process.env.OAUTH_PASSWORD_GRANT_ENABLED === "true";
export const PASSWORD_GRANT_USERS_JSON = process.env.OAUTH_PASSWORD_USERS_JSON;

export const SUPPORTED_SCOPES = [
  "openid"
];
